version: '3.7'

services:
  amarillo:
    image: ${DOCKER_IMAGE:?missing env var DOCKER_IMAGE}:${DOCKER_TAG:?missing env var DOCKER_TAG}
    networks:
      - public
    volumes:
      - amarillo-data:/app/data:rw
    environment:
      - RIDE2GO_TOKEN=${RIDE2GO_TOKEN:?missing env var RIDE2GO_TOKEN}
      - ADMIN_TOKEN=${ADMIN_TOKEN:?missing env var ADMIN_TOKEN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        traefik.enable: 'true'
        traefik.http.routers.amarillo.entrypoints: https
        traefik.http.routers.amarillo.rule: Host(`amarillo.bbnavi.de`)
        traefik.http.routers.amarillo.tls.certresolver: acme
        traefik.http.services.amarillo.loadbalancer.server.port: '80'

networks:
  public:
    external: true

volumes:
  amarillo-data:
    external: true
